language: c


os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - yasm

before_install:
  - export cc="gcc-4.9"

script:
  - 


jobs:
  include:
    - stage: Build
      script: ./configure --disable-sdl2 --disable-sdl && make
    - stage : Do Conformance Tests
      script: git clone https://github.com/jheulot/HEVCconformanceTest.git && \\
              ./configure --disable-sdl2 --disable-sdl && make \\
              cd HEVCconformanceTest && \\
              wget https://www.dropbox.com/sh/t737d4cuqakpphi/AADLyGfMWlP5IdtTr_TqclmTa?dl=1 -O files.zip && \\
              unzip files.zip -d avconv || true && \\
              pwd && ls -al && \\
              ruby runPattern.rb -dir avconv -exec ohplay
